// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfivsenfhmghxscyapvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmaXZzZW5maG1naHhzY3lhcHZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNjYzNDMsImV4cCI6MjA2MzY0MjM0M30.6_fI_tD_7THNfv1rdg-ViaRR2YhDdpRHZrGzK9tSC8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);